# Generated by Django 5.1.1 on 2024-10-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_active_product_dt_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dt_active',
            new_name='cs_active',
        ),
    ]
