# Generated by Django 5.1.1 on 2024-10-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_dt_active_product_cs_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dt_created',
            new_name='created',
        ),
    ]
