# Generated by Django 5.1.1 on 2024-10-09 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0005_rename_dt_active_client_cs_active'),
        ('employee', '0003_rename_dt_active_employee_cs_active'),
        ('product', '0003_rename_dt_active_product_cs_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('cs_active', models.BooleanField(db_column='cs_active', default=True)),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('dt_modified', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('nrf', models.CharField(db_column='nrf', max_length=255)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
