# Generated by Django 5.1.1 on 2024-10-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='dt_created',
            new_name='created',
        ),
    ]
