# Generated by Django 5.1.1 on 2024-10-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_active_employee_dt_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dt_active',
            new_name='cs_active',
        ),
    ]
