# Generated by Django 5.1.1 on 2024-10-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Client',
        ),
    ]
