# Generated by Django 5.1.1 on 2024-10-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_cliente_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
