# Generated by Django 5.1.1 on 2024-10-09 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='active',
            new_name='dt_active',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='created_at',
            new_name='dt_created',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='modified_at',
            new_name='dt_modified',
        ),
    ]
